# Generated by Django 4.0.4 on 2022-05-01 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weather_map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('danger_level', models.CharField(choices=[('ND', 'No Danger'), ('MD', 'Medium Danger Score'), ('HD', 'High Danger Score')], default='ND', max_length=2)),
                ('city', models.ForeignKey(help_text='Cities', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='weather_map.city')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Package name', max_length=256)),
                ('price', models.FloatField(help_text='Package price')),
                ('description', models.TextField(help_text='Package price', max_length=2048)),
                ('capacity', models.PositiveSmallIntegerField(blank=True, help_text='Maximum Capacity of travelers', null=True)),
                ('destination', models.ManyToManyField(to='tour_package.destination')),
            ],
        ),
        migrations.CreateModel(
            name='TourDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('tour_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_package.tourpackage')),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_package.destinationtype'),
        ),
    ]
