# Generated by Django 4.0.4 on 2022-05-01 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Country name', max_length=256)),
                ('continent', models.CharField(help_text='Continent name', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='City name', max_length=256)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Latest temperature recorded', max_digits=4, null=True)),
                ('temperature_timestamp', models.DateTimeField(blank=True, null=True)),
                ('country', models.ForeignKey(help_text='Countries', on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='weather_map.country')),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
    ]
